### ISSUE TITLE
How do with the  @Transient attribute

### ISSUE THREAD

**Issue by kengan** [infobip/infobip-spring-data-querydsl#18]
I use r2dbc  infobip-spring-data-querydsl. But in my entity I hava attribute with  @Transient, this attribute is not a table column.
But when I run the select , I get the error.
for example
My entity is as following

  @Table("customer_order")
  @Data
  @AllArgsConstructor
  @NoArgsConstructor
  
  public class OrderPO {
      @Id
      @Column("id")
      private Long id;
      @Column("customer_id")
      private Long customerId;
      @Column("customer_name")
      private String customerName;
      @Column("ordr_code")
      private String ordrCode;
      @Column("address")
      private String address;
      @Column("customer_mobile")
      private String customerMobile;
      @Column("total_pirce")
      private Float totalPirce;
      @Column("create_time")
      private LocalDateTime createTime;
    
      @Transient
      private List<OrderItemPO> orderItemList;
  
      public void create()
      {
          this.createTime=LocalDateTime.now();
      }
  }

I run following program

  Flux<OrderPO> orderPOFlux = orderDao.query(query ->query.
                select(orderDao.entityProjection()).
                from(qOrderPO).
                orderBy(qOrderPO.id.desc()).
                where(booleanBuilder).
                limit(pageSize).
                offset((page-1)*pageSize)).all();

I get error:

 Unknown column 'OrderPO.OrderItemList' in 'field list'
Error has been observed at the following site(s):
	|_ checkpoint ⇢ SQL "select OrderPO.id, OrderPO.customer_id, OrderPO.customer_name, OrderPO.ordr_code, OrderPO.address, OrderPO.customer_mobile, OrderPO.total_pirce, OrderPO.create_time, OrderPO.OrderItemList
from customer_order OrderPO
where OrderPO.id is not null
order by OrderPO.id desc
limit 1
offset 0" [DatabaseClient]

This error is not happen in JPA version. Can you help me? Thank you

**Comment by lpandzic** [comment]
`@Transient` is not currently supported (I'm looking into adding it), for first hand can you try if it works without this field?

**Comment by lpandzic** [comment]
Please try 5.0.5 and let me know if it works.

**Comment by lpandzic** [comment]
It takes time to sync to Maven Central, it's available now if you click on the badge in README.md (it shows 5.0.4 but maven central lists 5.0.5).

**Comment by kengan** [comment]
@lpandzic
I have try 5.0.5, but I get another error. My application can not run. The error show that my QuerydslR2dbcRepository about the entity with @transient can not been created.

my entity is as following
![image](https://user-images.githubusercontent.com/18627678/112238260-39007a80-8c7f-11eb-9950-fff28599b975.png)

my QuerydslR2dbcRepository  about this entity is as following
![image](https://user-images.githubusercontent.com/18627678/112238286-4f0e3b00-8c7f-11eb-88f5-095781100625.png)

when my application run I get error as following:

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'orderRespostoryImpl': Unsatisfied dependency expressed through field 'orderDao'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'orderDao' defined in com.cesc.demo.domain.order.repository.mapper.OrderDao defined in @EnableR2dbcRepositories declared on QuerydslR2dbcRepositoriesAutoConfigureRegistrar.EnableR2dbcRepositoriesConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
	... 35 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'orderDao' defined in com.cesc.demo.domain.order.repository.mapper.OrderDao defined in @EnableR2dbcRepositories declared on QuerydslR2dbcRepositoriesAutoConfigureRegistrar.EnableR2dbcRepositoriesConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
	... 49 more
Caused by: java.lang.NullPointerException
	at com.querydsl.core.types.ConstructorExpression.getParameterTypes(ConstructorExpression.java:58)
	at com.querydsl.core.types.ConstructorExpression.<init>(ConstructorExpression.java:72)
	at com.querydsl.core.types.Projections.constructor(Projections.java:122)
	at com.infobip.spring.data.r2dbc.QuerydslR2dbcRepositoryFactory.getConstructorExpression(QuerydslR2dbcRepositoryFactory.java:119)
	at com.infobip.spring.data.r2dbc.QuerydslR2dbcRepositoryFactory.getRepositoryFragments(QuerydslR2dbcRepositoryFactory.java:64)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepositoryComposition(RepositoryFactorySupport.java:371)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:276)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:230)
	at org.springframework.data.util.Lazy.get(Lazy.java:114)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:329)
	at org.springframework.data.r2dbc.repository.support.R2dbcRepositoryFactoryBean.afterPropertiesSet(R2dbcRepositoryFactoryBean.java:167)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 59 more

**Comment by kengan** [comment]
This error I have meet when I add  @QueryType(PropertyType.NONE) in front of  the  attribute with @transient . For example:
     @Transient
    @QueryType(PropertyType.NONE)
    private List<OrderItemPO> orderItemList;

Can you help me how to solve this problem. Thank you!

**Comment by kengan** [comment]
But after I change the version 5.0.4. The application can run and get the error as the first comment.

**Comment by lpandzic** [comment]
There's a bug in constructor discovery code. I'll let you know once it's fixed.

**Comment by lpandzic** [comment]
Can you try with 5.1.0 (it should be available soon)?
Here's example test code - https://github.com/infobip/infobip-spring-data-querydsl/tree/master/infobip-spring-data-r2dbc-querydsl/src/test/java/com/infobip/spring/data/r2dbc/transientannotation

**Comment by lpandzic** [comment]
@kengan have you tried 5.1.0?

**Comment by kengan** [comment]
@lpandzic
I have tried 5.1.0. Everything is Ok. Thank you very much!

**Comment by lpandzic** [comment]
You're welcome.
