### ISSUE TITLE
Spring Data JDBC: support for `Embedded` entities?

### ISSUE THREAD

**Issue by dirkluijk** [infobip/infobip-spring-data-querydsl#35]
Are embedded entities for Spring Data JDBC supported? https://docs.spring.io/spring-data/jdbc/docs/current/reference/html/#jdbc.entity-persistence.embedded-entities

I don't see it mentioned anywhere, but it doesn't seem to work for me, using Kotlin classes:

```kotlin

data class SomeEntity @PersistenceConstructor constructor(
        @Id @JvmField
        var id: UUID? = null,

        // ...

        @Embedded(onEmpty = Embedded.OnEmpty.USE_EMPTY)
        val event: AuditEvent,

        // ...
)

data class AuditEvent @PersistenceConstructor constructor(
        val eventType: String,
        val eventId: String,
        val auditDateTime: OffsetDateTime = now()
)
```

Generated class:
```java
/**
 * QSomeEntity is a Querydsl query type for QSomeEntity
 */
@Generated("com.querydsl.sql.codegen.MetaDataSerializer")
public class QSomeEntity extends com.querydsl.sql.RelationalPathBase<QSomeEntity> {

    private static final long serialVersionUID = -1427592166;
    public static final QSomeEntity someEntity = new QSomeEntity("SomeEntity");

    public final ComparablePath<java.util.UUID> id = createComparable("id", java.util.UUID.class);

    // ...

    public final SimplePath<AuditEvent> event = createSimple("event", AuditEvent.class);

    // ...
}
```

The problem is that it tries to query for the column `event` which does not exists. It should query for `event_type`, `event_id` and `audit_date_time` instead.

I'm using version `5.4.2` with Spring Data JDBC.

**Comment by lpandzic** [comment]
They aren't - the main reason probably being located here:
https://github.com/infobip/infobip-spring-data-querydsl/blob/c1b6926919520b70c8fa2f40e59ad2afca3de489/infobip-spring-data-jdbc-annotation-processor-common/src/main/java/com/infobip/spring/data/jdbc/annotation/processor/SpringDataJdbcAnnotationProcessorBase.java#L84-L90
and here
https://github.com/infobip/infobip-spring-data-querydsl/blob/c1b6926919520b70c8fa2f40e59ad2afca3de489/infobip-spring-data-jdbc-annotation-processor-common/src/main/java/com/infobip/spring/data/jdbc/annotation/processor/SpringDataJdbcConfiguration.java#L23-L32 meaning that embedded annotation is not passed to Querydsl.

**Comment by lpandzic** [comment]
It seems it's not as simple as that - I'll look into it.

**Comment by dirkluijk** [comment]
Cool. Let me know if I can help with something.

**Comment by lpandzic** [comment]
Unfortunately, Querydsl SQL module doesn't have any kind of embedded support and class/fields are 1:1 to tables/columns  or at least that is my understanding.
However, I was able to modify `infobip-spring-data-jdbc-annotation-processor` to inline `@Embedded` annotated class properties so it matches 1:1 with the tables but side effect is that queries don't match 1:1 object model.

I've released [6.1.0.M1](https://s01.oss.sonatype.org/content/repositories/releases/com/infobip/infobip-spring-data-jdbc-querydsl/6.1.0.M1/), can you try it out and let me know if it works for you?

**Comment by dirkluijk** [comment]
Awesome! I pulled in `6.1.0.M1`, but I see no changes in the generated classes; any chance that your changes were accidentally not included in the release?

**Comment by lpandzic** [comment]
Yeah, I've accidentaly released on wrong branch, sorry about that.
Can you try 6.1.0.M2?

**Comment by dirkluijk** [comment]
It works perfect, this solution was exactly what I was looking for!

Any chance of releasing this fix/feature on 5.x? I am still running on an older version of Spring Boot.

**Comment by lpandzic** [comment]
Honestly I'd like to avoid doing that if possible as:
* new features in general should attract people to newer versions, not the other way around
* doing it once opens up the request attack surface of people requesting it every time.

Do you have problems running it with Spring Boot 2.4.1?

**Comment by dirkluijk** [comment]
No problem, I will upgrade to newest Spring version, thanks! 😄

**Comment by lpandzic** [comment]
Ok :), but seriously, do you have any problems running it with older version of Spring Boot? I wouldn't expect so - I don't remember using any new APIs or something being backwards incompatible...

PS: I need to update README.md and then I'll release 6.1.0.

**Comment by dirkluijk** [comment]
I was originally using your version `5.4.2` with Spring Boot `2.4.8` and Spring Data JDBC `2.1.8`.
Then I tried your solution `6.1.0.M2` with Spring Boot `2.5.1` and Spring Data JDBC `2.2.1`.

Both were running fine.

**Comment by dirkluijk** [comment]
Running `6.1.0.M2` with Spring Boot `2.4.8` and Spring Data JDBC `2.1.8` gave me:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.querydsl.sql.SQLTemplates]: Factory method 'sqlTemplates' threw exception; nested exception is java.lang.NoSuchMethodError: 'com.querydsl.core.types.Operation com.querydsl.core.types.ExpressionUtils.operation(java.lang.Class, com.querydsl.core.types.Operator, java.util.List)'
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 172 more
Caused by: java.lang.NoSuchMethodError: 'com.querydsl.core.types.Operation com.querydsl.core.types.ExpressionUtils.operation(java.lang.Class, com.querydsl.core.types.Operator, java.util.List)'
	at com.querydsl.sql.SQLOps.<clinit>(SQLOps.java:98)
	at com.querydsl.sql.SQLTemplates.<clinit>(SQLTemplates.java:41)
	at com.querydsl.sql.SQLTemplatesRegistry.getBuilder(SQLTemplatesRegistry.java:61)
	at com.querydsl.sql.SQLTemplatesRegistry.getTemplates(SQLTemplatesRegistry.java:33)
	at com.infobip.spring.data.common.InfobipSpringDataCommonConfiguration.sqlTemplates(InfobipSpringDataCommonConfiguration.java:23)
	at com.infobip.spring.data.common.InfobipSpringDataCommonConfiguration$$EnhancerBySpringCGLIB$$827dcf80.CGLIB$sqlTemplates$0(<generated>)
	at com.infobip.spring.data.common.InfobipSpringDataCommonConfiguration$$EnhancerBySpringCGLIB$$827dcf80$$FastClassBySpringCGLIB$$aa4aede2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.infobip.spring.data.common.InfobipSpringDataCommonConfiguration$$EnhancerBySpringCGLIB$$827dcf80.sqlTemplates(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 173 more
```

**Comment by dirkluijk** [comment]
I fixed it by explicitly specifying version `5.0.0` for `querydsl-core` and `querydsl-apt`.

**Comment by lpandzic** [comment]
6.1.0 is out!

**Comment by dirkluijk** [comment]
Awesome!
