### ISSUE TITLE
Spring Data JDBC:  Embedded Entity and ProjectTableCaseFormat is not working

### ISSUE THREAD

**Issue by codering** [infobip/infobip-spring-data-querydsl#41]
Hi , this is all my config:

### maven dependency

```xml

 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.4</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

...

 <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-core</artifactId>
            <version>5.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
            <version>5.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.infobip</groupId>
            <artifactId>infobip-spring-data-jdbc-querydsl-boot-starter</artifactId>
            <version>6.1.2</version>
        </dependency>

```

### JdbcConfig

```java
@Configuration
@ProjectTableCaseFormat(CaseFormat.LOWER_UNDERSCORE)
@ProjectColumnCaseFormat(CaseFormat.LOWER_UNDERSCORE)
public class JdbcConfig extends AbstractJdbcConfiguration {

    @Bean
    NamingStrategy namingStrategy() {
        return new NamingStrategy(){
            @Override
            public String getTableName(Class<?> type) {
                return NamingStrategy.super.getTableName(type);
            }

            @Override
            public String getReverseColumnName(RelationalPersistentProperty property) {
                return NamingStrategy.super.getReverseColumnName(property).toLowerCase() + "_id";
            }

            @Override
            public String getKeyColumn(RelationalPersistentProperty property) {
                return "sort_order";
            }
        };
    }
}

```

### Main
```java

@SpringBootApplication
public class QuerydslDemoApplication {

    public static void main(String[] args) {
        ConfigurableApplicationContext ctx = SpringApplication.run(QuerydslDemoApplication.class, args);
        AuthProviderRepository repository = ctx.getBean(AuthProviderRepository.class);
   
        Object resp = repository.queryMany(q -> q
                .select(repository.entityProjection())
                .from(authProvider));
        System.out.println(resp);
    }
}

```

### Entities

```java

@Getter
@AllArgsConstructor
public class AuthProvider {

    @Id
    private Long id;
    private Long tenantId;
    private String name;
    private String endpoint;
    private String healthUrl;

    @Embedded.Empty
    private SecretInfo secretInfo;

    @MappedCollection(idColumn = "auth_provider_id", keyColumn = "authorized_at")
    private Iterable<AuthorizedTenant> authorizedTenants;

}


@Value
@Builder
public class AuthorizedTenant {

    @Id
    @With
    private Long id;
    private Long tenantId;
    private Long authorizedAt;

}

@Value(staticConstructor = "from")
public class SecretInfo {

    private String accessKey;
    private String secretKey;

}

```

### Repository

```java

public interface AuthProviderRepository extends QuerydslJdbcRepository<AuthProvider, Long> {

}


```

The errror message :

```

...
Caused by: com.querydsl.core.QueryException: Caught SQLSyntaxErrorException for select AuthProvider.Id, AuthProvider.TenantId, AuthProvider.Name, AuthProvider.Endpoint, AuthProvider.HealthUrl, AuthProvider.SecretInfo, AuthProvider.AuthorizedTenants
from AuthProvider AuthProvider
...

Caused by: java.sql.SQLSyntaxErrorException: Table 'mydb.authprovider' doesn't exist

``` 

If I use `@Table` on Entity class for customizing, like `@Table("auth_provider")`, then errror message is : 

```

Caused by: com.querydsl.core.QueryException: Caught SQLSyntaxErrorException for select AuthProvider.id, AuthProvider.tenant_id, AuthProvider.name, AuthProvider.endpoint, AuthProvider.health_url, AuthProvider.secret_info, AuthProvider.authorized_tenants
from auth_provider AuthProvider
	at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:50)
	at com.querydsl.sql.Configuration.translate(Configuration.java:507)
	at com.querydsl.sql.AbstractSQLQuery.getResults(AbstractSQLQuery.java:311)
	at com.infobip.spring.data.jdbc.QuerydslJdbcPredicateExecutor.query(QuerydslJdbcPredicateExecutor.java:175)
	at com.infobip.spring.data.jdbc.QuerydslJdbcPredicateExecutor.queryMany(QuerydslJdbcPredicateExecutor.java:163)

...

Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'AuthProvider.secret_info' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
...

```

**Comment by codering** [comment]
I changed Embedded usage :

```java

@Table("auth_provider")
@Getter
@AllArgsConstructor
public class AuthProvider  {

    @Id
    private Long id;
    private Long tenantId;
    private String name;
    private String endpoint;
    private String healthUrl;

    @Embedded(onEmpty = Embedded.OnEmpty.USE_EMPTY)
    private SecretInfo secretInfo;

    @MappedCollection(idColumn = "auth_provider_id", keyColumn = "authorized_at")
    private Iterable<AuthorizedTenant> authorizedTenants;


```

and error message is :

```
Caused by: com.querydsl.core.QueryException: Caught SQLSyntaxErrorException for select AuthProvider.id, AuthProvider.tenant_id, AuthProvider.name, AuthProvider.endpoint, AuthProvider.health_url, AuthProvider.access_key, AuthProvider.secret_key, AuthProvider.authorized_tenants
from auth_provider AuthProvider
	at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:50)
	at com.querydsl.sql.Configuration.translate(Configuration.java:507)
	at com.querydsl.sql.AbstractSQLQuery.getResults(AbstractSQLQuery.java:311)
	at com.infobip.spring.data.jdbc.QuerydslJdbcPredicateExecutor.query(QuerydslJdbcPredicateExecutor.java:175)
	at com.infobip.spring.data.jdbc.QuerydslJdbcPredicateExecutor.queryMany(QuerydslJdbcPredicateExecutor.java:163)
...

Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'AuthProvider.authorized_tenants' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)


```

so the `MappedCollection` is not support ?

**Comment by lpandzic** [comment]
Yes, `@MappedCollection` currently isn't supported.
Can you please provide a sample project that reproduces the issue? That would significantly reduce work required to reproduce those issues.

**Comment by codering** [comment]
If I use maven compile,  it's working. 
But if I just use IDEA  build, sometimes it not, especially when I modify the entity class. I need rebuild again.

**Comment by lpandzic** [comment]
That is weird - are you passing -parameters argument to your compiler in both IDE and maven?
[Note the requirements of the module](https://github.com/infobip/infobip-spring-data-querydsl#-requirements).

**Comment by lpandzic** [comment]
I'll be closing this one due to inactivity. Feel free to reopen.
