### ISSUE TITLE
How to ignore fields when updating

### ISSUE THREAD

**Issue by tianyu94** [infobip/infobip-spring-data-querydsl#43]
```java
    @CreatedBy
    @JsonIgnore
    private Long createdBy;

    @CreatedDate
    @JsonIgnore
    private LocalDateTime createdDate;
```

Is there any way to ignore then (raw sql is contains: `set created_by = null, set created_date = null`) when updating.

```
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'created_by' cannot be null
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.26.jar:8.0.26]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.26.jar:8.0.26]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.26.jar:8.0.26]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[mysql-connector-java-8.0.26.jar:8.0.26]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[mysql-connector-java-8.0.26.jar:8.0.26]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1350) ~[mysql-connector-java-8.0.26.jar:8.0.26]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) ~[mysql-connector-java-8.0.26.jar:8.0.26]
```

**Comment by lpandzic** [comment]
You mean like transient fields that are not present in the table?

**Comment by tianyu94** [comment]
> You mean like transient fields that are not present in the table?

Only when updating, When I call `org.springframework.data.repository.CrudRepository#save` the generated SQL has `created` fields, But they only exist when they are created, Is this spring-data-jdbc's auditing bug?

**Comment by lpandzic** [comment]
It's possible but you have to do it manually by specifying a projection in your query that doesn't have the fields you don't need. Default projection contains all fields, example of customization is here - https://github.com/infobip/infobip-spring-data-querydsl#JDBCProjections.

**Comment by lpandzic** [comment]
Hm, not sure about updates though (this is only for select), it'd have to have tighter integration with Spring Data JDBC.

**Comment by tianyu94** [comment]
It may be a spring-data-jdbc problem, I can only temporarily attach the corresponding field when updating to avoid it being empty
