### ISSUE TITLE
IllegalArgumentException: Did not find a static field of the same type in class org.example.entity.QExamInfo

### ISSUE THREAD

**Issue by githubyong** [infobip/infobip-spring-data-querydsl#59]
infobip-spring-data-jdbc-querydsl-boot-starter: 6.2.1
querydsl-maven-plugin:4.1.4

log details:
```
Caused by: java.lang.IllegalArgumentException: Did not find a static field of the same type in class org.example.entity.QExamInfo
	at com.infobip.spring.data.common.QuerydslExpressionFactory.getRelationalPathBaseFromQueryClass(QuerydslExpressionFactory.java:131)
	at com.infobip.spring.data.common.QuerydslExpressionFactory.getRelationalPathBaseFromQueryRepositoryClass(QuerydslExpressionFactory.java:114)
	at com.infobip.spring.data.jdbc.QuerydslJdbcRepositoryFactory.getRepositoryFragments(QuerydslJdbcRepositoryFactory.java:70)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepositoryComposition(RepositoryFactorySupport.java:434)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:300)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:322)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:230)
```

because the generated bean use upper camel:
```
public class QExamInfo extends com.querydsl.sql.RelationalPathBase<ExamInfo> {

    private static final long serialVersionUID = -401254998;

    public static final QExamInfo ExamInfo = new QExamInfo("ExamInfo");

    public final StringPath applyDate = createString("applyDate");

    public final StringPath applyDoctor = createString("applyDoctor");

```

while the com.infobip.spring.data.common.QuerydslExpressionFactory#getRelationalPathBaseFromQueryClass use lower camel
```
   private RelationalPathBase<?> getRelationalPathBaseFromQueryClass(Class<?> queryClass) {
        String fieldName = CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_CAMEL, queryClass.getSimpleName().substring(1));
        Field field = ReflectionUtils.findField(queryClass, fieldName);

        if (field == null) {
            throw new IllegalArgumentException("Did not find a static field of the same type in " + queryClass);
        }
```

**Comment by githubyong** [comment]
my maven plugin  like this
```
<plugin>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-maven-plugin</artifactId>
                <version>4.1.4</version>
                <configuration>
                    <jdbcDriver>com.mysql.jdbc.Driver</jdbcDriver>
                    <jdbcUrl>xx</jdbcUrl>
                    <jdbcUser>xx</jdbcUser>
                    <jdbcPassword>xx</jdbcPassword>
                    <packageName>org.example.entity</packageName>
                    <targetFolder>${project.basedir}/target/generated-sources</targetFolder>
                    <sourceFolder>src/main/resources</sourceFolder>
                    <exportBeans>true</exportBeans>
                    <beanAddToString>true</beanAddToString>
                    <beanPackageName>org.example.entity</beanPackageName>
                    <tableNamePattern>ExamInfo,Report</tableNamePattern>
                    <customTypes>
                        <customType>com.querydsl.sql.types.UtilDateType</customType>
                    </customTypes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>5.1.35</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <goals>
                            <goal>export</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <parameters>true</parameters>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>

```

**Comment by lpandzic** [comment]
You shouldn't need maven plugin to generate Q classes with `infobip-spring-data-jdbc-querydsl-boot-starter`. Annotation processor should kick in and generate the Q classes without connecting to the database. Can you try removing`querydsl-maven-plugin` definition?

**Comment by githubyong** [comment]
> You shouldn't need maven plugin to generate Q classes with `infobip-spring-data-jdbc-querydsl-boot-starter`. Annotation processor should kick in and generate the Q classes without connecting to the database. Can you try removing`querydsl-maven-plugin` definition?

I use the  maven plugin generate both DataObject And Q classes.

**Comment by lpandzic** [comment]
Can you provide a github repo that reproduces the issue please?

**Comment by githubyong** [comment]
I found that then table name is all upper name (eg:STUDENT),the Q class field generated by querydsl-maven-plugin will use lower word.
` public static final QStudent student = new QStudent("STUDENT");`

when the table name is camel case,the Q class field generated by querydsl-maven-plugin will use came word.
`
public static final QStudent Student = new QStudent("Student");
`

**Comment by lpandzic** [comment]
This project is intended to be used with annotation processor - not the maven plugin.

**Comment by githubyong** [comment]
> This project is intended to be used with annotation processor - not the maven plugin.

is there have a guide or example to use processor ?

**Comment by lpandzic** [comment]
https://github.com/infobip/infobip-spring-data-querydsl#-annotation-processor

Annotation processor is included by default with `infobip-spring-data-jdbc-querydsl-boot-starter`.
For all classes with `@Id` annotation it should automatically generate Q classes.
For more details check the annotation processor section in readme.md.
