### ISSUE TITLE
Parameter 0 of method setReactiveTransactionManager in com.infobip.spring.data.r2dbc.QuerydslR2dbcRepositoryFactoryBean required a bean of type 'org.springframework.transaction.ReactiveTransactionManager' that could not be found.

### ISSUE THREAD

**Issue by newbalancer** [infobip/infobip-spring-data-querydsl#68]
Hi 

I use to ` implementation("com.infobip:infobip-spring-data-r2dbc-querydsl-boot-starter:6.2.0")` 

The project could not be executed due to the following error.

I wonder if you know how to fix it. 

thanks

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method setReactiveTransactionManager in com.infobip.spring.data.r2dbc.QuerydslR2dbcRepositoryFactoryBean required a bean of type 'org.springframework.transaction.ReactiveTransactionManager' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.transaction.ReactiveTransactionManager' in your configuration.
```

--------

this code is kotlin configuration 

```kotlin 
@Configuration
@EnableR2dbcRepositories(
    basePackages = [
        "com.example.webflux.repository"
    ]
)
class R2dbcDataSourceConfiguration constructor(
    @Qualifier("read.datasource-com.example.webflux.config.ReadDataSourceProperties")
    private val readDataSourceProperties: BaseDataSourceProperties,
    @Qualifier("write.datasource-com.example.webflux.config.WriteDataSourceProperties")
    private val writeDataSourceProperties: BaseDataSourceProperties,
) : AbstractR2dbcConfiguration() {

    @Bean(name = ["connectionFactory"])
    override fun connectionFactory(): ConnectionFactory = MultiRoutingConnectionFactory().apply {

        val factories: HashMap<String, ConnectionFactory> = hashMapOf(
            WriteDataSourceProperties.KEY to writeConnectionFactory(),
            ReadDataSourceProperties.KEY to readConnectionFactory()
        )

        this.setTargetConnectionFactories(factories)

        this.setDefaultTargetConnectionFactory(writeConnectionFactory())
    }

    @Bean(name = ["writeConnectionFactory"])
    fun writeConnectionFactory() = getConnectionFactory(properties = writeDataSourceProperties)


    @Bean(name = ["readConnectionFactory"])
    fun readConnectionFactory() = getConnectionFactory(properties = readDataSourceProperties)

    private fun getConnectionFactory(properties: BaseDataSourceProperties): ConnectionFactory {

        val options: ConnectionFactoryOptions = ConnectionFactoryOptions.builder()
            .option(DRIVER, properties.driver())
            .option(HOST, properties.host())
            .option(PORT, properties.port())
            .option(USER, properties.username())
            .option(PASSWORD, properties.password())
            .option(DATABASE, properties.database()) 
            .option(CONNECT_TIMEOUT, Duration.ofSeconds(3))
            .build()

        return ConnectionFactories.get(options)
    }

    @Bean
    fun transactionManager(
        @Qualifier("connectionFactory")
        connectionFactory: ConnectionFactory,
    ): TransactionManager = R2dbcTransactionManager(connectionFactory)
}
```

**Comment by newbalancer** [comment]
changed  transactionManager to reactiveTransactionManager

```kotlin 
    @Bean
    fun reactiveTransactionManager(
        @Qualifier("connectionFactory")
        connectionFactory: ConnectionFactory,
    ): ReactiveTransactionManager = R2dbcTransactionManager(connectionFactory)
```

---- 

but other error checked 

The project could not be executed due to the following error.

I wonder if you know how to fix it.

thanks

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'itemQuerydslRepository' defined in com.example.webflux.querydsl.ItemQuerydslRepository defined in @EnableR2dbcRepositories declared on QuerydslR2dbcRepositoriesAutoConfigureRegistrar.EnableR2dbcRepositoriesConfiguration: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/mapping/PreferredConstructor$Parameter
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.21.jar:5.3.21]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.21.jar:5.3.21]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.21.jar:5.3.21]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.21.jar:5.3.21]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.21.jar:5.3.21]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.21.jar:5.3.21]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.21.jar:5.3.21]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:936) ~[spring-beans-5.3.21.jar:5.3.21]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.21.jar:5.3.21]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.21.jar:5.3.21]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.1.jar:2.7.1]
	at com.example.webflux.BootApplicationKt.main(BootApplication.kt:15) ~[main/:na]
Caused by: java.lang.NoClassDefFoundError: org/springframework/data/mapping/PreferredConstructor$Parameter
	at com.infobip.spring.data.common.PreferredConstructorDiscoverer$Discoverers.buildPreferredConstructor(PreferredConstructorDiscoverer.java:103) ~[infobip-spring-data-common-6.2.0.jar:na]
	at com.infobip.spring.data.common.PreferredConstructorDiscoverer$Discoverers.access$200(PreferredConstructorDiscoverer.java:33) ~[infobip-spring-data-common-6.2.0.jar:na]
	at com.infobip.spring.data.common.PreferredConstructorDiscoverer$Discoverers$2.lambda$discover$3(PreferredConstructorDiscoverer.java:77) ~[infobip-spring-data-common-6.2.0.jar:na]
	at java.base/java.util.Optional.orElseGet(Optional.java:369) ~[na:na]
	at com.infobip.spring.data.common.PreferredConstructorDiscoverer$Discoverers$2.discover(PreferredConstructorDiscoverer.java:67) ~[infobip-spring-data-common-6.2.0.jar:na]
	at com.infobip.spring.data.common.PreferredConstructorDiscoverer.discover(PreferredConstructorDiscoverer.java:30) ~[infobip-spring-data-common-6.2.0.jar:na]
	at com.infobip.spring.data.common.QuerydslExpressionFactory.getConstructor(QuerydslExpressionFactory.java:95) ~[infobip-spring-data-common-6.2.0.jar:na]
	at com.infobip.spring.data.common.QuerydslExpressionFactory.getConstructorExpression(QuerydslExpressionFactory.java:28) ~[infobip-spring-data-common-6.2.0.jar:na]
	at com.infobip.spring.data.r2dbc.QuerydslR2dbcRepositoryFactory.getRepositoryFragments(QuerydslR2dbcRepositoryFactory.java:70) ~[infobip-spring-data-r2dbc-querydsl-6.2.0.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepositoryComposition(RepositoryFactorySupport.java:436) ~[spring-data-commons-2.7.1.jar:2.7.1]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:301) ~[spring-data-commons-2.7.1.jar:2.7.1]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323) ~[spring-data-commons-2.7.1.jar:2.7.1]
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:231) ~[spring-data-commons-2.7.1.jar:2.7.1]
	at org.springframework.data.util.Lazy.get(Lazy.java:115) ~[spring-data-commons-2.7.1.jar:2.7.1]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:329) ~[spring-data-commons-2.7.1.jar:2.7.1]
	at org.springframework.data.r2dbc.repository.support.R2dbcRepositoryFactoryBean.afterPropertiesSet(R2dbcRepositoryFactoryBean.java:179) ~[spring-data-r2dbc-1.5.1.jar:1.5.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.21.jar:5.3.21]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.21.jar:5.3.21]
	... 16 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.data.mapping.PreferredConstructor$Parameter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	... 34 common frames omitted
```

this Repository is not working 

how setting to Repository?

What does `@EnableQuerydslR2dbcRepositories` mean?

```kotlin
@Repository
interface ItemQuerydslRepository : QuerydslR2dbcRepository<Item, Long> {
}
```

**Comment by newbalancer** [comment]
before issue 

version update after fixed 

thanks
